name: CMakeNightly

on:
  workflow_dispatch:
  schedule:
    # Mon-Fri 00:30AM
    - cron: '30 0 * * 1-5'

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    # Convert this to a build matrix for cross-platform testing
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/Build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}
      
# TODO: Package the build for publishing
